camera0: 38580376
camera1: 39725782
frame_width: 1280
frame_height: 720
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1
checkerboard_box_size_scale : 17.4
checkerboard_rows: 4
checkerboard_columns: 10
cooldown: 100